language: node_js
node_js:
  - 10.11.0
os:
  - linux
  - osx
before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - npm install -g typescript vsce
install:
  - npm install
  - npm run vscode:prepublish
  - vsce package
script:
  - unset npm_config_prefix
  - npm test
  - ls -ll *vsix
deploy:
  provider: releases
  api_key:
    secure: Ll6LyJZ63D037zVA3nnGxFtPL4bViOzLxVTfNNrbt2fbRYFlUAMLOnGy9ETleWvkCSR7qBdk8rnQ3ZxWJlnCOJW1VsV12Wvz+EvDxxiglxTpgxikHdNkjkrmKBbTjvxB+Kp1Fpo6IpysUBhLKngLp4Vdv6Xbj/vhALKN5yeTrDB7DaKjG7mTW5vnVLn93OarOIfCnIeX8grbm+jxE52rp3sKocdFE4YpHRJXo3vsP70Yjl+jy9HtjREF6GI6skunkiQoOYiYKLOLNdx2QALPWSbTq/pjuNd2fx7NJIWiecP/R0qvMtVMBv89OT2epBSMNV/DJHhwTv5XMUWa694yq9U1hsm1K3SVI/BVizuMM9w2zMrJiYcAagXEkuigwuzyY2sXa1n88e+A2o3CLVCXGbq7Z3k/SxKoIhCbPm6YzucJaW5WPLz6eq9xA1cZG/9hhDTn9GaF1861inGzf+iSyPDCgaeJ9cdpW9QfQWMVePtsM7ZjOVSSbDXzRk+MFBjzDxu4hgshoZAsjNO9IMPWnZdt7gLFcjlL+qN6N7cqwsP2evpekVPUKbJuhpvVrcnPorKI42yWWLfzDX2R5VxLMBdeP0T28BmawJNkoe0JOMeTzkIlY+hyHEWksiOV8fIrgvkCsXgiASiSUjz8m3AqFruwa/qPEyms36fwAlCTHsQ=
  file: languagetool-linter-*.vsix
  file_glob: true
  on:
    condition: $TRAVIS_OS_NAME == "linux"
    repo: davidlday/vscode-languagetool-linter
    branch: master
    tags: true
after_deploy:
  - vsce publish -p $PERSONAL_ACCESS_TOKEN
env:
  global:
    secure: Mwd4kNlDeXoFy8qJYl2QxfJ84UCm+/EwGwJE3q96rqT/AKx/kNFGXbzTdASbr6Wgh1rTmeREi5zc5NEyLTlj/M80Jn2vUKaIuCGuighfnOw+b9lt0PBmWyfMfRUpAsK8VhDayCBTJn+QxMbA+2bIDOB6QUgveDgaUNAMgeSZyig+kEDFjnKTUBDAZclojFZfHpA58vvVVViIixrx1q4fhTv0R5bzKMqaz62gwzEZ43oJ2AddP7voLjbvdGVew5l+kD4LSYVix8E1o6n4F7Vg4seLvXw8abk9zY24eeSZIGqEpGPHac88wBVRJz11ZorEVGUaJ9nux2HLlVsTzqGfVK/pkWF+oD+P+Y2ByMsPQXhI69EwVGAkS+HzVgztdRL+OQaNR57B6r+HomZZmCtBLls7hwetuZ86Ep4kTifrwhGULfwaFcvjk6T5dwKPhjxyp2wdZxRFXu8fpFNg5KK0vG/HcgRYe4DfQ9z70UFcpWzmr2iINR0NfqtMc+B44OxsDvT0sv9SUoN7Ms/Rz3OQ7S6hhHv5pT0G2r2Xt1q1XQdaMrj/IHKnvBTd3XiQQ3qQaAAZ4VHjUjUifOiZcsxlDkE+OV3I2Q4JfTm2yQTlc+yHNtVCNf3t3wWn/u0f3s+WWo33LGZOgqXgOPrNLqhP+m23SKfFwrYsqLBM9RnK4BU=
