name: Build on Push

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: set display on ubuntu-latest
      if: matrix.os == 'ubuntu-latest'
      run: |
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      env:
        CI: true
    - name: npm install, build, and test on ${{ matrix.os }}
      run: |
        npm install -g typescript vsce
        npm install
        vsce package
        npm run vscode:prepublish
        npm test
      env:
        CI: true

